# Developer Server Configuration.
muleInfo:
  version: 1.0.0 (Development)

# Logging settings.
logging:
  level: INFO
  loggers:
    net.sf.zoftwhere:
      level: DEBUG
    net.sf.zoftwhere.mule:
      level: DEBUG
    org.hibernate:
      level: WARN
    org.hibernate.SQL:
      level: DEBUG
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
      logFormat: "%-5p [%d{ISO8601,CAT}] %c: %m%n%rEx"
    - type: file
      threshold: INFO
      currentLogFilename: _target/application.log
      archivedLogFilenamePattern: _target/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MiB
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"

# Server Settings
server:
  applicationContextPath: /mule-shell
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /dev-admin
  adminConnectors:
    - type: http
      port: 8081

# Database Settings
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/mule?currentSchema=public
  user: mule-admin
  password:
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.physical_naming_strategy: net.sf.zoftwhere.hibernate.SnakeCaseNamingStrategy
    hibernate.globally_quoted_identifiers: true
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: false
    hibernate.format_sql: false

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
viewRendererConfiguration:
  freemarker:
    strict_syntax: yes
    whitespace_stripping: yes

viewAssetPath:
  bootstrapCSS: '<link rel="stylesheet" href="/mule-shell/assets/bootstrap-4.3.1.min.css">'
  bootstrapJS: '<script src="/mule-shell/assets/bootstrap-4.3.1.min.js"></script>'
  jQueryJS: '<script src="/mule-shell/assets/jquery-3.4.1.min.js"></script>'
  jQuerySlimJS: '<script src="/mule-shell/assets/jquery-3.4.1.min.js"></script>'
  popperJS: '<script src="/mule-shell/assets/popper-1.14.7.min.js"></script>'

#metrics:
#  reporters:
#    - type: graphite
#      host: localhost
#      port: 2003
#      prefix: example
#      frequency: 1m